//! 更新默认主题配置后，需要执行 npm run build:theme 重新构建index.json

const fs = require('fs')
const path = require('path')
const { createThemeColors } = require('./utils')

const defaultThemes = [
  {
    id: 'obsidian_glass',
    name: '黑曜星芒 · OLED 旗舰',
    isDark: true,
    config: {
      primary: 'rgb(16, 185, 129)',
      font: 'rgb(243, 244, 246)',
      'c-app-background': '#07090e',
      'c-main-background': '#0a0d14',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#f59e0b',
      'c-badge-secondary': '#10b981',
      'c-badge-tertiary': '#34d399',
    },
  },
  {
    id: 'silk_ivory',
    name: '皓月凝霜 · 象牙白瓷',
    isDark: false,
    config: {
      primary: 'rgb(5, 150, 105)',
      font: 'rgb(15, 23, 42)',
      'c-app-background': '#f8fafc',
      'c-main-background': '#ffffff',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#10b981',
      'c-badge-secondary': '#059669',
      'c-badge-tertiary': '#047857',
    },
  },
  {
    id: 'braun_bauhaus',
    name: '德意志工业 · 迪特·拉姆斯',
    isDark: false,
    config: {
      primary: 'rgb(255, 85, 0)',
      font: 'rgb(26, 26, 26)',
      'c-app-background': '#f5f5f0',
      'c-main-background': '#ffffff',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#ff5500',
      'c-badge-secondary': '#3b82f6',
      'c-badge-tertiary': '#10b981',
    },
  },
  {
    id: 'retro_walkman',
    name: '复古卡带机 · 随身听 1980',
    isDark: true,
    config: {
      primary: 'rgb(255, 111, 0)',
      font: 'rgb(240, 240, 240)',
      'c-app-background': '#0f172a',
      'c-main-background': '#131e33',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#ff6f00',
      'c-badge-secondary': '#0284c7',
      'c-badge-tertiary': '#f59e0b',
    },
  },
  {
    id: 'cyberpunk_neon',
    name: '银翼杀手 · 赛博霓虹',
    isDark: true,
    config: {
      primary: 'rgb(0, 240, 255)',
      font: 'rgb(255, 255, 255)',
      'c-app-background': '#0b0818',
      'c-main-background': '#110d24',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#ff007f',
      'c-badge-secondary': '#00f0ff',
      'c-badge-tertiary': '#a855f7',
    },
  },
  {
    id: 'cosmic_nebula',
    name: '宇宙深空 · 星际漫游',
    isDark: true,
    config: {
      primary: 'rgb(217, 70, 239)',
      font: 'rgb(248, 250, 252)',
      'c-app-background': '#03050a',
      'c-main-background': '#070a14',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#d946ef',
      'c-badge-secondary': '#8b5cf6',
      'c-badge-tertiary': '#38bdf8',
    },
  },
  {
    id: 'sakura_dusk',
    name: '晚樱落月 · 新海诚物语',
    isDark: true,
    config: {
      primary: 'rgb(244, 114, 182)',
      font: 'rgb(253, 242, 248)',
      'c-app-background': '#1a1024',
      'c-main-background': '#231530',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#f472b6',
      'c-badge-secondary': '#fbbf24',
      'c-badge-tertiary': '#c084fc',
    },
  },
  {
    id: 'eva_mecha',
    name: '初号机觉醒 · 泛用机甲',
    isDark: true,
    config: {
      primary: 'rgb(0, 255, 102)',
      font: 'rgb(245, 245, 245)',
      'c-app-background': '#130820',
      'c-main-background': '#1a0b2c',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#00ff66',
      'c-badge-secondary': '#ff6600',
      'c-badge-tertiary': '#a855f7',
    },
  },
  {
    id: 'song_celadon',
    name: '千里江山 · 青绿天青',
    isDark: true,
    config: {
      primary: 'rgb(45, 212, 191)',
      font: 'rgb(240, 253, 250)',
      'c-app-background': '#0c1714',
      'c-main-background': '#11201c',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#2dd4bf',
      'c-badge-secondary': '#10b981',
      'c-badge-tertiary': '#f59e0b',
    },
  },
  {
    id: 'bamboo_mist',
    name: '竹影清风 · 苍翠江南',
    isDark: false,
    config: {
      primary: 'rgb(22, 163, 74)',
      font: 'rgb(20, 35, 25)',
      'c-app-background': '#f0fdf4',
      'c-main-background': '#ffffff',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#16a34a',
      'c-badge-secondary': '#059669',
      'c-badge-tertiary': '#10b981',
    },
  },
  {
    id: 'forbidden_city',
    name: '紫禁朱雀 · 故宫丹心',
    isDark: true,
    config: {
      primary: 'rgb(245, 158, 11)',
      font: 'rgb(255, 251, 235)',
      'c-app-background': '#1c080a',
      'c-main-background': '#260c0f',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#f59e0b',
      'c-badge-secondary': '#e11d48',
      'c-badge-tertiary': '#fbbf24',
    },
  },
  {
    id: 'teenage_op1',
    name: '极客合成器 · 少年工程',
    isDark: false,
    config: {
      primary: 'rgb(255, 51, 102)',
      font: 'rgb(30, 30, 30)',
      'c-app-background': '#e5e7eb',
      'c-main-background': '#f3f4f6',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#ff3366',
      'c-badge-secondary': '#00ccff',
      'c-badge-tertiary': '#33ff77',
    },
  },
  {
    id: 'monet_garden',
    name: '莫奈花园 · 塞纳睡莲',
    isDark: false,
    config: {
      primary: 'rgb(99, 102, 241)',
      font: 'rgb(30, 27, 75)',
      'c-app-background': '#fffbeb',
      'c-main-background': '#ffffff',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#6366f1',
      'c-badge-secondary': '#ec4899',
      'c-badge-tertiary': '#f59e0b',
    },
  },
  {
    id: 'okinawa_salt',
    name: '冲绳海浪 · 盐系薄荷',
    isDark: false,
    config: {
      primary: 'rgb(14, 165, 233)',
      font: 'rgb(12, 74, 96)',
      'c-app-background': '#f0fdfa',
      'c-main-background': '#ffffff',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',
      'c-badge-primary': '#0ea5e9',
      'c-badge-secondary': '#14b8a6',
      'c-badge-tertiary': '#06b6d4',
    },
  },
  {
    id: 'green',
    name: '绿意盎然',
    isDark: false,
    config: {
      primary: 'rgb(77, 175, 124)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#4baed5',
      'c-badge-tertiary': '#e7aa36',
    },
  },
  {
    id: 'blue',
    name: '蓝田生玉',
    isDark: false,
    config: {
      primary: 'rgb(52, 152, 219)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#5cbf9b',
      'c-badge-tertiary': '#5cbf9b',
    },
  },
  {
    id: 'blue_plus',
    name: '蛋雅深蓝',
    isDark: false,
    config: {
      primary: 'rgb(77, 131, 175)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-600)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': 'rgba(66.6, 150.7, 171, 1)',
      'c-badge-tertiary': 'rgba(54, 196, 231, 1)',
    },
  },
  {
    id: 'orange',
    name: '橙黄橘绿',
    isDark: false,
    config: {
      primary: 'rgb(245, 171, 53)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#9ed458',
      'c-badge-tertiary': '#9ed458',
    },
  },
  {
    id: 'brown',
    name: '泥牛入海',
    isDark: false,
    config: {
      primary: 'rgba(188, 128, 68, 1)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#483472',
      'c-badge-tertiary': '#647D39',
    },
  },
  {
    id: 'red',
    name: '热情似火',
    isDark: false,
    config: {
      primary: 'rgb(214, 69, 65)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#dfbb6b',
      'c-badge-tertiary': '#dfbb6b',
    },
  },
  {
    id: 'pink',
    name: '粉装玉琢',
    isDark: false,
    config: {
      primary: 'rgb(241, 130, 141)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#f5b684',
      'c-badge-tertiary': '#f5b684',
    },
  },
  {
    id: 'purple',
    name: '重斤球紫',
    isDark: false,
    config: {
      primary: 'rgb(155, 89, 182)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#e5a39f',
      'c-badge-tertiary': '#e5a39f',
    },
  },
  {
    id: 'grey',
    name: '灰常美丽',
    isDark: false,
    config: {
      primary: 'rgb(108, 122, 137)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#b19b9f',
      'c-badge-tertiary': '#b19b9f',
    },
  },
  {
    id: 'ming',
    name: '青出于黑',
    isDark: false,
    config: {
      primary: 'rgb(51, 110, 123)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#6376a2',
      'c-badge-tertiary': '#6376a2',
    },
  },
  {
    id: 'blue2',
    name: '清热板蓝',
    isDark: false,
    config: {
      primary: 'rgb(79, 98, 208)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#b080db',
      'c-badge-tertiary': '#b080db',
    },
  },
  {
    id: 'black',
    name: '黑灯瞎火',
    isDark: true,
    config: {
      primary: 'rgb(190, 190, 190)',
      font: 'rgb(255, 255, 255)',
      'c-app-background': 'rgba(0, 0, 0, 0)',
      'c-main-background': 'rgba(19, 19, 19, 0.95)',
      'bg-image': 'landingMoon.png',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary-dark-200)',
      'c-badge-secondary': 'var(c-primary)',
      'c-badge-tertiary': 'var(c-primary-dark-300)',
    },
  },
  {
    id: 'mid_autumn',
    name: '月里嫦娥',
    isDark: false,
    config: {
      primary: 'rgb(74, 55, 82)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'rgba(255, 255, 255, 0)',
      'c-main-background': 'rgba(255, 255, 255, 0.9)',
      'bg-image': 'jqbg.jpg',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',


      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#af9479',
      'c-badge-tertiary': '#af9479',
    },
  },
  {
    id: 'naruto',
    name: '木叶之村',
    isDark: false,
    config: {
      primary: 'rgb(87, 144, 167)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'rgba(255, 255, 255, 0.15)',
      'c-main-background': 'rgba(255, 255, 255, 0.8)',
      'bg-image': 'myzcbg.jpg',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': 'var(c-primary-light-100)',
      'c-badge-tertiary': 'var(c-primary-light-100)',
    },
  },
  {
    id: 'china_ink',
    name: '近墨者黑',
    isDark: false,
    config: {
      primary: 'rgba(47, 47, 47, 1)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'rgba(255, 255, 255, 0)',
      'c-main-background': 'rgba(255, 255, 255, 0.8)',
      'bg-image': 'china_ink.jpg',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',


      'c-badge-primary': 'rgba(137, 70, 70, 1)',
      'c-badge-secondary': 'rgba(67, 139, 65, 1)',
      'c-badge-tertiary': 'rgba(132, 135, 65, 1)',
    },
  },
  {
    id: 'happy_new_year',
    name: '新年快乐',
    isDark: false,
    config: {
      primary: 'rgb(192, 57, 43)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'rgba(255, 255, 255, 0.15)',
      'c-main-background': 'rgba(255, 255, 255, 0.8)',
      'bg-image': 'xnkl.png',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': '#7fb575',
      'c-badge-secondary': '#dfbb6b',
      'c-badge-tertiary': 'var(c-primary-light-100)',
    },
  },
]

const themes = defaultThemes.map(({ config: { primary, font, ...extInfo }, ...themeInfo }) => {
  return {
    ...themeInfo,
    isCustom: false,
    config: {
      themeColors: createThemeColors(primary, font, themeInfo.isDark),
      extInfo,
    },
  }
})

fs.writeFileSync(path.join(__dirname, 'themes.ts'), `/* eslint-disable */\n//! 此文件由 createThemes.js 生成\n\nexport default ${JSON.stringify(themes, null, 2)} as const`)

